### ISSUE TITLE
How to train my custom dataset?

### ISSUE THREAD

**Issue by JavierClearImageAI** [saic-vul/adaptis#20]
I have been unable to train my custom data set of images downloaded from the web. I transformet the dataset using the  cocodataset/panopticapi but I haven't been able to make it work. I guess I need to resize the images at some point?

```
Starting Epoch: 0
Total Epochs: 1
0%|                                                                        | 0/71 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_toy_logs.py", line 138, in <module>
    start_epoch=args.start_epoch)
  File "train_toy_logs.py", line 126, in train
    trainer.training(epoch)
  File "/home/ubuntu/adaptis-pytorch/adaptis/engine/trainer.py", line 98, in training
    for i, batch_data in enumerate(tbar):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1080 and 1040 in dimension 2 at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/TH/generic/THTensor.cpp:689

0%|                                                                        | 0/71 [00:14<?, ?it/s]

```

Thanks a lot

**Comment by JavierClearImageAI** [comment]
I managed to train my custom dataset by getting my dataset in the same format that their dataset. I.e, from my instance segmentation data, I converted to panoptic using the coco panoptic api, then made some other transformations:
1. I resized the images so they all have the same size. 
2. I selected one channel per image (all three are the same), instead of the three given by the panoptic API).

That's basically all. 

You probably need to use torch transformations if you want to transform your images in the fly. In the end pytorch require for the training to be fed with images with the same size. Therefore, you have two options: Either you do it with torch transformations in the fly or you do it separately. That's up to you. For deployment torch transforms before and after seem better, so you can get the final images in the original size, but it was much easier for my trial to just use PIL.resize().

@saic-vul please let me know if you are interested in implementing it to your pipeline, since I am going to work on it. Otherwise I will just keep it on my local machine.

I'll keep you posted :)
