### ISSUE TITLE
Inference error?? (cityscape data)

### ISSUE THREAD

**Issue by edwardcho** [saic-vul/adaptis#25]
Hello Sir,

I ran train cityscapes and got model.
Then I tried inference.. 

But I met some error...

At first, my inference code is as follows.
```python
import cv2
import sys
import mxnet as mx
from tqdm import tnrange
import os

sys.path.insert(0, '..')
from adaptis.inference.adaptis_sampling import get_panoptic_segmentation
from adaptis.inference.prediction_model import AdaptISPrediction

ctx = mx.gpu(0)

# init dataset
from adaptis.data.cityscapes import CityscapesDataset

dataset_path = '/data/TESTBOARD/additional_networks/segmentation/semantic_segmentation_likelyjourney_pytorch_modify/datasets/cityscapes'
dataset = CityscapesDataset(dataset_path, split='test', with_segmentation=True)

# load model
from adaptis.model.cityscapes.models import get_cityscapes_model

norm_layer = mx.gluon.nn.BatchNorm
model = get_cityscapes_model(num_classes=19, norm_layer=norm_layer, backbone='resnet50')

pmodel = AdaptISPrediction(model, dataset)

weights_path = '/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/experiments/cityscapes/000/checkpoints/last_checkpoint.params'
pmodel.load_parameters(weights_path, ctx)

dense_sampling_params = {
    'thresh1': 0.70,
    'thresh2': 0.60,
    'ithresh': 0.3,
    'fl_prob': 0.10,
    'fl_eps': 0.003,
    'fl_blur': 2,
    'max_iters': 2000,
    'cut_radius': 40
}

image_path = os.path.join(dataset_path, 'leftImg8bit/test/berlin', 'berlin_000494_000019_leftImg8bit.png')
print(image_path)

image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

pred = get_panoptic_segmentation(pmodel, image,
                                 sampling_algorithm='proposals',
                                 use_flip=True, **dense_sampling_params)

print(pred['proposals_info'])
```

Error message..
```python
Traceback (most recent call last):
  File "test_cityscapes_model.py", line 49, in <module>
    use_flip=True, **dense_sampling_params)
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/inference/adaptis_sampling.py", line 57, in get_panoptic_segmentation
    use_flip=use_flip, **sampling_params)
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/inference/adaptis_sampling.py", line 177, in predict_instances_with_proposals
    width=image_shape[1], height=image_shape[0])[0, 0]
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/inference/prediction_model.py", line 85, in get_proposals_map
    out = self.net.proposals_head(*features)
TypeError: 'NoneType' object is not callable
```

What should I do for this error??

Thanks...

**Comment by edwardcho** [comment]
Hello Sir..

I modified code in adaptis/inference/prediction_model.py
   out = self.net.proposas_head(*features)
  =>
  out = self.net._proposas_head(*features)

But I met another error...
```python
Traceback (most recent call last):
  File "test_cityscapes_model.py", line 49, in <module>
    use_flip=True, **dense_sampling_params)
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/inference/adaptis_sampling.py", line 57, in get_panoptic_segmentation
    use_flip=use_flip, **sampling_params)
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/inference/adaptis_sampling.py", line 177, in predict_instances_with_proposals
    width=image_shape[1], height=image_shape[0])[0, 0]
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/inference/prediction_model.py", line 85, in get_proposals_map
    out = self.net._proposals_head(*features)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 925, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/model/basic_blocks.py", line 96, in hybrid_forward
    return self.layers(x)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 925, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/nn/basic_layers.py", line 117, in hybrid_forward
    x = block(x)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 925, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/data/TESTBOARD/additional_networks/segmentation/instance_segmentation_adaptis_saicvul_mxnet/adaptis/model/basic_blocks.py", line 116, in hybrid_forward
    return self.body(x)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 925, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/nn/basic_layers.py", line 117, in hybrid_forward
    x = block(x)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 918, in forward
    params = {i: j.data(ctx) for i, j in self._reg_params.items()}
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 918, in <dictcomp>
    params = {i: j.data(ctx) for i, j in self._reg_params.items()}
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 543, in data
    return self._check_and_get(self._data, ctx)
  File "/home/mirero/anaconda3/lib/python3.7/site-packages/mxnet/gluon/parameter.py", line 240, in _check_and_get
    "nested child Blocks"%(self.name))
RuntimeError: Parameter 'sepconvhead1_conv0_weight' has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks
```

Thanks....

**Comment by edwardcho** [comment]
Hello Sir,

I have some questions.

1. When predict, I should do initialize AdaptISPrediction.
   The constructor of AdaptISPrediction should have dataset as input parameter.
   I don't know this reason.
   If I want to predict 1 image, Should I do this parameter that is trainning data folder??

Thanks...

**Comment by riazspace** [comment]
@edwardcho Hi, can you share your trained model of CITYSCAPES with me?
