### ISSUE TITLE
Freeze after a few batches

### ISSUE THREAD

**Issue by cruigo93** [saic-vul/adaptis#4]
![Screenshot from 2019-10-08 18-57-54](https://user-images.githubusercontent.com/9817816/66397423-9e19cf00-e9fd-11e9-8b4e-2883a79555e9.png)

**Comment by ksofiyuk** [comment]
Try to run with workers=0 on 1 GPU. Is there freeze then?

**Comment by cruigo93** [comment]
still freezing

**Comment by cruigo93** [comment]
![Screenshot from 2019-10-09 11-12-40](https://user-images.githubusercontent.com/9817816/66453326-c3522000-ea85-11e9-825a-f49b9ed301fa.png)

**Comment by cruigo93** [comment]
I have instance mask with each number represented each object, and different segmentation mask with each number represented each class of object. 

    def __init__(self, dataset_path, split='train', **kwargs):
        super(ToyDataset, self).__init__(**kwargs)

        self.dataset_path = Path(dataset_path)
        self.dataset_split = split

        self.dataset_samples = []
        # img_paths  = []
        images_path = sorted((self.dataset_path / split).rglob('images/*.jpg'))
        for image_path in images_path:
            image_path = str(image_path)
            mask_path = image_path[:-4].replace('images', 'masks')
            json_path = image_path[:-4].replace('images', 'jsons')+'_labels.json'
            self.dataset_samples.append((image_path, mask_path, json_path))

    def get_sample(self, index):
        image_path, mask_path, json_path = self.dataset_samples[index]

        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        instances_mask = cv2.imread(mask_path+'.png', cv2.IMREAD_UNCHANGED).astype(np.int32)

        sample = {'image': image}
        if self.with_segmentation:
            semantic_segmentation = cv2.imread(mask_path+'_seg.png', cv2.IMREAD_UNCHANGED).astype(np.int32)
            label_dict = json.load(open(json_path, 'r'))
            sample['semantic_segmentation'] = semantic_segmentation
        else:
            instances_mask += 1

        instances_ids = get_unique_labels(instances_mask, exclude_zero=True)
        instances_info = {
            x: {'class_id': label_dict[str(x)], 'ignore': False}
            for x in instances_ids
        }

        sample.update({
            'instances_mask': instances_mask,
            'instances_info': instances_info,
        })
        
        # print(self.from_dataset_mapping)
        # print(sample)
        return sample

    @property
    def stuff_labels(self):
        return [0]

    @property
    def things_labels(self):
        return [1, 2, 3, 4]

**Comment by ksofiyuk** [comment]
MXNet also may freeze if the model doesn't fit in GPU memory. Try to reduce batch size or crop size.

**Comment by ksofiyuk** [comment]
Maybe there is a problem with instances_mask. If there are very large numbers there, the program will hang on np.bincount. Print np.unique(instances_mask.flatten()) to debug it.
P.S. MXNet also may freeze if the model doesn't fit in GPU memory. Try to reduce batch size or crop size.

**Comment by cruigo93** [comment]
Just tried to use 128*128 binary mask instead of multi with number of instances less than 10, the same it stops just after start

**Comment by wangxiao5791509** [comment]
(adaptis) wangxiao@wx:~/Downloads/AdaptIS/adaptis-master$ python3 train_toy_v2.py --batch-size=14 --workers=2
Using CPU
Namespace(batch_size=14, checkpoints_path=PosixPath('experiments/toy_v2/004/checkpoints'), ctx=cpu(0), dataset_path='/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis_toy_v2_128x128/', dtype='float32', exp_name='', gpus='', kvstore='local', logs_path=PosixPath('experiments/toy_v2/004/logs'), ngpus=1, no_cuda=True, no_exp=False, run_path=PosixPath('experiments/toy_v2/004'), start_epoch=0, thread_pool=False, val_batch_size=8, weights=None, workers=2)
AdaptIS(
  (_proposals_head): ConvHead(
    (layers): HybridSequential(
      (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (2): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (4): Conv2D(None -> 1, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (feature_extractor): UNet(
    (image_bn): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=3)
    (d0): HybridSequential(
      (0): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (1): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
    )
    (d1): HybridSequential(
      (0): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=True, global_pool=False, pool_type=max, layout=NCHW)
      (1): HybridSequential(
        (0): HybridSequential(
          (0): Conv2D(None -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
        (1): HybridSequential(
          (0): Conv2D(None -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
      )
    )
    (d2): HybridSequential(
      (0): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=True, global_pool=False, pool_type=max, layout=NCHW)
      (1): HybridSequential(
        (0): HybridSequential(
          (0): Conv2D(None -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
        (1): HybridSequential(
          (0): Conv2D(None -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
      )
    )
    (d3): HybridSequential(
      (0): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=True, global_pool=False, pool_type=max, layout=NCHW)
      (1): HybridSequential(
        (0): HybridSequential(
          (0): Conv2D(None -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
        (1): HybridSequential(
          (0): Conv2D(None -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
      )
    )
    (d4): HybridSequential(
      (0): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=True, global_pool=False, pool_type=max, layout=NCHW)
      (1): HybridSequential(
        (0): HybridSequential(
          (0): Conv2D(None -> 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
        (1): HybridSequential(
          (0): Conv2D(None -> 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): Activation(relu)
          (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        )
      )
    )
    (u3): up_block(
      (upsampler): Conv2DTranspose(1 -> 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), groups=256, bias=False)
      (conv1): HybridSequential(
        (0): Conv2D(None -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_0): HybridSequential(
        (0): Conv2D(None -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_1): HybridSequential(
        (0): Conv2D(None -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
    )
    (u2): up_block(
      (upsampler): Conv2DTranspose(1 -> 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), groups=128, bias=False)
      (conv1): HybridSequential(
        (0): Conv2D(None -> 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_0): HybridSequential(
        (0): Conv2D(None -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_1): HybridSequential(
        (0): Conv2D(None -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
    )
    (u1): up_block(
      (upsampler): Conv2DTranspose(1 -> 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), groups=64, bias=False)
      (conv1): HybridSequential(
        (0): Conv2D(None -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_0): HybridSequential(
        (0): Conv2D(None -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_1): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
    )
    (u0): up_block(
      (upsampler): Conv2DTranspose(1 -> 32, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), groups=32, bias=False)
      (conv1): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_0): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
      (conv3_1): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): Activation(relu)
        (2): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
    )
    (fe): HybridSequential(
      (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (2): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
    )
  )
  (adaptis_head): ToyAdaptISHead(
    (eqf): ExtractQueryFeatures(
    
    )
    (controller_net): SimpleConvController(
      (layers): HybridSequential(
        (0): Conv2D(None -> 32, kernel_size=(1, 1), stride=(1, 1), Activation(relu))
        (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        (2): Conv2D(None -> 32, kernel_size=(1, 1), stride=(1, 1), Activation(relu))
        (3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
        (4): Conv2D(None -> 32, kernel_size=(1, 1), stride=(1, 1), Activation(relu))
        (5): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=None)
      )
    )
    (add_coord_features): AppendCoordFeatures(
    
    )
    (block0): HybridSequential(
      (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (2): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (4): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (5): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
    )
    (adain): AdaIN(
      (affine_scale): Dense(None -> 32, linear)
      (affine_bias): Dense(None -> 32, linear)
    )
    (block1): HybridSequential(
      (0): Conv2D(None -> 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=16)
      (2): Conv2D(None -> 1, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (segmentation_head): ConvHead(
    (layers): HybridSequential(
      (0): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (1): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (2): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (3): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (4): Conv2D(None -> 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), Activation(relu))
      (5): BatchNorm(axis=1, eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, in_channels=32)
      (6): Conv2D(None -> 2, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
Starting Epoch: 0
Total Epochs: 160
0%|                                                                       | 0/714 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_toy_v2.py", line 131, in <module>
    start_epoch=args.start_epoch)
  File "train_toy_v2.py", line 122, in train
    trainer.training(epoch)
  File "/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis/engine/trainer.py", line 125, in training
    losses, losses_logging, splitted_batch_data, outputs = self.batch_forward(batch_data)
  File "/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis/engine/trainer.py", line 211, in batch_forward
    splitted_batch = {k: gluon.utils.split_and_load(v, ctx_list=self.args.ctx, even_split=False) for k, v in batch_data.items()}
  File "/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis/engine/trainer.py", line 211, in <dictcomp>
    splitted_batch = {k: gluon.utils.split_and_load(v, ctx_list=self.args.ctx, even_split=False) for k, v in batch_data.items()}
  File "/home/wangxiao/anaconda2/envs/adaptis/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 116, in split_and_load
    if len(ctx_list) == 1:
TypeError: object of type 'Context' has no len()



@cruigo93   I can not run this code successfully. Do you how to solve this problem? Thanks.

**Comment by Arkkienkeli** [comment]
It froze for me when I didn't have a corresponding mask file for an image. You could check your dataset for that.

**Comment by cruigo93** [comment]
@wangxiao5791509 I was not able to solve problem with freezing

**Comment by ksofiyuk** [comment]
@cruigo93 Figure out the exact line on which program hangs. You can do it using debugger (or simple using debug by printing). Then put print before this line with input arguments (along with shapes, if there are tensors) for the command on which the program hangs, send these logs.

**Comment by cruigo93** [comment]
well it freezes just after 
`if self.hybridize_model and not hybridize:
                self.net.hybridize()
                hybridize = True`
and somewhere before start another iteration of for in trainer.train
I mean 
`for i, batch_data in enumerate(tbar):
print(f"{i}/{len(tbar)}")`
I am really sorry for possible stupid questions

**Comment by cruigo93** [comment]
Maybe there is some special preprocessing which is not obvious for me?

**Comment by GuptaSonam** [comment]
hey, were you able to solve this? I am also facing the similar issue when training on cityscapes dataset.

**Comment by cruigo93** [comment]
Nope, still waiting for answer because it's open

**Comment by cruigo93** [comment]
Updates: 
First, I use Pytorch implementation now. Second, I reduced dataset size. And It works now, but still I wonder what was the problem

**Comment by ste928z** [comment]
I had this problem with images containing zero instances. 
After filtering these images out from the dataset the training does not freeze anymore.

**Comment by ptrvilya** [comment]
The issue is likely related to images with empty object masks, as augmentation will loop forever on these trying to sample non-empty mask. A quick fix is to set [keep_background_prob](https://github.com/saic-vul/adaptis/blob/c20270833c0fb171038115469faa5c556d28ae41/adaptis/data/base.py#L21) slightly larger than zero (e.g. 0.1), therefore allowing to sample empty masks with low probability.
