### ISSUE TITLE
TypeError: object of type 'Context' has no len()

### ISSUE THREAD

**Issue by wangxiao5791509** [saic-vul/adaptis#6]
Starting Epoch: 0
Total Epochs: 160
0%|                                                                      | 0/1250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_toy_v2.py", line 131, in <module>
    start_epoch=args.start_epoch)
  File "train_toy_v2.py", line 122, in train
    trainer.training(epoch)
  File "/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis/engine/trainer.py", line 127, in training
    losses, losses_logging, splitted_batch_data, outputs = self.batch_forward(batch_data)
  File "/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis/engine/trainer.py", line 213, in batch_forward
    splitted_batch = {k: gluon.utils.split_and_load(v, ctx_list=self.args.ctx, even_split=False) for k, v in batch_data.items()}
  File "/home/wangxiao/Downloads/AdaptIS/adaptis-master/adaptis/engine/trainer.py", line 213, in <dictcomp>
    splitted_batch = {k: gluon.utils.split_and_load(v, ctx_list=self.args.ctx, even_split=False) for k, v in batch_data.items()}
  File "/home/wangxiao/anaconda2/envs/adaptis/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 116, in split_and_load
    if len(ctx_list) == 1:
TypeError: object of type 'Context' has no len()

Hi, I can run this code successfully, due to the ctx issue. I am new to mxnet, please help. Thanks.

**Comment by ptrvilya** [comment]
The issue was with creating of CPU context, we've removed no-cuda flag because training on CPU is not supported.
